server:
  port: 8081

spring:
  application:
    name: product-service
  mongodb:
    uri: mongodb://localhost:27017/products
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

nats: 
  url: nats://localhost:4222

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO